/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Server;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Random;

import mainfunction.Vertify;

/**
 *
 * @author Nguyen Phong
 */
public class ServerGui extends javax.swing.JFrame {

    /**
     * Creates new form ServerGui
     */
    public ServerGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        gStatus = new javax.swing.JLabel();
        gIp = new javax.swing.JLabel();
        gPort = new javax.swing.JLabel();
        gBtc = new javax.swing.JLabel();
        gBtcQuatiza = new javax.swing.JLabel();
        gFuzzyTransfor = new javax.swing.JLabel();
        gFuzzyApply = new javax.swing.JLabel();
        gStartBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gKeyDecode = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Ke Decode");

        jLabel8.setText("Status");

        gStatus.setText("sts");

        gIp.setText("ip");

        gPort.setText("port");

        gBtc.setText("btc");

        gBtcQuatiza.setText("btc quatization");

        gFuzzyTransfor.setText("recived data");

        gFuzzyApply.setText("result");

        gStartBtn.setText("Start");
        gStartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gStartBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("IP");

        jLabel2.setText("Port");

        jLabel3.setText("BTC");

        jLabel4.setText("BTC Quatization");

        jLabel5.setText("Fuzzy Transfor");

        gKeyDecode.setText("key");

        jLabel6.setText("Fuzzy Apply");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gStartBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gStatus)
                            .addComponent(gIp)
                            .addComponent(gPort)
                            .addComponent(gBtc)
                            .addComponent(gBtcQuatiza)
                            .addComponent(gFuzzyTransfor)
                            .addComponent(gFuzzyApply)
                            .addComponent(gKeyDecode))
                        .addGap(0, 536, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gStartBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(gStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(gIp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(gPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(gBtc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(gBtcQuatiza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gFuzzyTransfor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(gFuzzyApply))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(gKeyDecode))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void gStartBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    	startServer();
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerGui().setVisible(true);
            }
        });
    }
    
    
    ServerThread serverThread;
    void startServer(){
    	serverThread = new ServerThread();
		Thread t = new Thread(serverThread);
		t.setDaemon(true);
		serverThread.runnable = true;
		t.start();
    }
	
	class ServerThread implements Runnable{

		Socket socket;
	    protected volatile boolean runnable = false;
	    public boolean enrollment = false;
	    public boolean authentication = false;
		@Override
		public void run() {
			// TODO Auto-generated method stub
			try{
				System.out.println("The capitalization server is running.");
		        int clientNumber = 0;
		        ServerSocket listener = new ServerSocket(1512);
		        InetAddress iAddress = InetAddress.getLocalHost();
		        String currentIp = iAddress.getHostAddress();
		        System.out.println("Current IP address : " +currentIp); //gives only host address
		        gStatus.setText("Server Started!!");
		        gIp.setText(currentIp);
		        gPort.setText("1512");
		        gBtc.setText(readFile("BTC.txt", StandardCharsets.UTF_8));
		        try {
		            while (true) {
		                new Capitalizer(listener.accept(), clientNumber++).start();
		            }
		        } finally {
		            listener.close();
		        }
			}catch(Exception ex){
				
			}
		}
    	String readFile(String path, Charset encoding) 
  			  throws IOException 
		{
		  byte[] encoded = Files.readAllBytes(Paths.get(path));
		  return new String(encoded, encoding);
		}
	}

	private class Capitalizer extends Thread{
		private Socket socket;
        private int clientNumber;
        double[] BTC;

        public Capitalizer(Socket socket, int clientNumber) {
            this.socket = socket;
            this.clientNumber = clientNumber;
            readBTC();
            log("New connection with client# " + clientNumber + " at " + socket);
            gStatus.setText("New connection with client# " + clientNumber + " at " + socket);
        }
        

    	String readFile(String path, Charset encoding) 
    			  throws IOException 
    			{
    			  byte[] encoded = Files.readAllBytes(Paths.get(path));
    			  return new String(encoded, encoding);
    			}
    	public void readBTC(){
    		try {
    			String content = readFile("BTC.txt", StandardCharsets.UTF_8);
    			BTC = convertToDoubleAr(content);
    		} catch (IOException e) {
    			// TODO Auto-generated catch block
    			e.printStackTrace();
    		}
    	}
    	double[] convertToDoubleAr(String input){
    		if(input == null)
    			return null;
    		String[] tempArray = input.split(" ");
    		double[] result = new double[tempArray.length];
    		for(int i = 0;i<tempArray.length;i++){
    			result[i] = Double.parseDouble(tempArray[i]);
    		}
    		return result;
    	}
    	
    	int[] getRealKey(int[] key){
    		int[] result = new int[key.length];
    		for(int i = 0;i<key.length;i++){
    			result[i] = key[i]/60;
    		}
    		return result;
    	}

        /**
         * Services this thread's client by first sending the
         * client a welcome message then repeatedly reading strings
         * and sending back the capitalized version of the string.
         */
        public void run() {
            try {

                // Decorate the streams so we can send characters
                // and not just bytes.  Ensure output is flushed
                // after every newline.
                BufferedReader in = new BufferedReader(
                        new InputStreamReader(socket.getInputStream()));
                PrintWriter out = new PrintWriter(socket.getOutputStream(), true);

                // Get messages from the client, line by line; return them
                // capitalized
                while (true) {
                    String input = in.readLine();
                    log("input:"+input);
                    String respone = "";
                    if (input.equals("getna")) {
                    	respone = generaNA();
                    }
                    if(input.equals("enrollment")){
                    	String BTCs = in.readLine();
                    	fileUtils.writetofile("BTC.txt", BTCs);
                    	gBtc.setText(BTCs);
                    	BTC = convertToDoubleAr(BTCs);
                    	//fileUtils.writetofile("S.txt", in.readLine());
                    	respone = "enrollment_success";
                    }else if(input.equals("authentication")){
                    	String fuzzyTranforRecived = in.readLine();
                    	gFuzzyTransfor.setText(fuzzyTranforRecived);
                    	Vertify vrt = new Vertify();
                    	int[] decodeCommitValue = new int[BTC.length], quatizaBio = new int[BTC.length];
                    	int[] keyDecode = vrt.vertify(BTC, getString2IntA(fuzzyTranforRecived), decodeCommitValue, quatizaBio);
                    	respone = Arrays.toString(keyDecode);
                    	gKeyDecode.setText(Arrays.toString(getRealKey(keyDecode)));
                    	gBtc.setText(Arrays.toString(BTC));
                    	gBtcQuatiza.setText(Arrays.toString(quatizaBio));
                    	gFuzzyApply.setText(Arrays.toString(decodeCommitValue));
                    }
                    out.println(respone);
                }
            } catch (IOException e) {
                log("Error handling client# " + clientNumber + ": " + e);
            } finally {
                try {
                    socket.close();
                } catch (IOException e) {
                    log("Couldn't close a socket, what's going on?");
                }
                log("Connection with client# " + clientNumber + " closed");
            }
        }
        
        int[] getString2IntA(String content){
        	String[] cnt = content.split(" ");
        	int[] result = new int[cnt.length];
        	for(int i = 0; i<result.length;i++){
        		result[i] = Integer.parseInt(cnt[i]);
        	}
        	return result;
        }
        
        String generaNA(){
        	String result = "";
    		Random rand = new Random();
    		for(int i = 0;i < 200;i++){
    			result+= rand.nextDouble();
    			if(i!=199)
    				result+=" ";
    		}
        	return result;
        }

        /**
         * Logs a simple message.  In this case we just write the
         * message to the server applications standard output.
         */
        private void log(String message) {
            System.out.println(message);
        }
	}


    // Variables declaration - do not modify                     
    private javax.swing.JLabel gBtc;
    private javax.swing.JLabel gBtcQuatiza;
    private javax.swing.JLabel gFuzzyApply;
    private javax.swing.JLabel gFuzzyTransfor;
    private javax.swing.JLabel gIp;
    private javax.swing.JLabel gKeyDecode;
    private javax.swing.JLabel gPort;
    private javax.swing.JButton gStartBtn;
    private javax.swing.JLabel gStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration                   
}
