
version: '3.3'

#networks:
#  artifacts:
#    driver: overlay
#    attachable: true

services:

  ca.org1.amazonaws.com:
    image: hyperledger/fabric-ca:x86_64-1.0.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.amazonaws.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e921772b429967db9bc357801df55672cd1ed6cbee3f02856fbfd85b2bad0372_sk


      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.amazonaws.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e921772b429967db9bc357801df55672cd1ed6cbee3f02856fbfd85b2bad0372_sk


    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../Channel/crypto-config/peerOrganizations/org1.amazonaws.com/ca/:/etc/hyperledger/fabric-ca-server-config
    #networks:
    #  - artifacts
    container_name: ca_peerOrg1